#!/bin/bash

#################
# Boot tweaking #
#################

# Sets noop scheduler during boot
echo noop > /sys/block/mmcblk0/queue/scheduler

# Activate ondemand governor on every available CPU
echo ondemand | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor >/dev$

# Set swappiness to 0
echo 0 > /proc/sys/vm/swappiness

# Local cover art support
# For Mpdroid. The path to music is http://xxx.xxx.xxx.xxx:8080/music/
mongoose -listening_port 8080 -document_root /var/www/covers
#
# For Mpod or Mpad. Cover server address to http://xxx.xxx.xxx.xxx:8080
#mongoose -listening_port 8080 -document_root /var/www/Music

# Unmute mixer & set volume to 100%
amixer scontrols | sed -e 's/^Simple mixer control//' | while read line; do
	amixer sset "'Digital',0" 100%
	amixer sset "'Analogue Playback Boost',0" 0%
done

